# Generated by Django 5.1.5 on 2025-01-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'В ожидании'), ('READY', 'Готов'), ('PAID_FOR', 'Оплаченный')], default='WAITING', max_length=10)),
                ('items', models.ManyToManyField(related_name='order_meals', to='order.meal')),
            ],
        ),
    ]
