# Generated by Django 5.1.5 on 2025-01-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('', '----------'), ('WAITING', 'В ожидании'), ('READY', 'Готов'), ('PAID_FOR', 'Оплаченный')], default='WAITING', max_length=10),
        ),
    ]
